services:
  web:
    build: .
    environment:
      - PYTHONPATH=/code
      - DEBUG=False
      - ALLOWED_HOSTS=0.0.0.0,localhost
    container_name: django_web
    volumes:
      - .:/code
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/static
    ports:
      - "8080:80"
    depends_on:
      - web